server:
  port: 8002 # 服务端口


#spirng基础配置
spring:
  redis:
    port: 6379
    host: 47.115.35.176
    database: 0
    password: 1410357039
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
  profiles:
    active: dev # 环境设置
  application:
    name: service-core # 服务名
  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://110.42.224.240:3306/fxb?useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: 6AxUi94j82ICyPkq97HnNVnxdnhBKkZs
  #设置json日期统一返回格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #微服务注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 110.42.224.240:8848 # nacos服务地址

#mybatis配置
mybatis-plus: #mybatis
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #日志输出配置
  mapper-locations: classpath:com/jzj/core/mapper/xml/*.xml  #xml文件位置

#服务调用
feign:
  client:
    config:
      default:
        connectTimeout: 10000 #连接超时配置
        readTimeout: 600000 #执行超时配置

#腾讯云
tencent:
  npl:
    secretId: AKIDRo9DzWytymLBn9bSGo4rQkuxpRnsxRXF
    secretKey: RgfOq45rOo3N3Td3j8HDuMZeeT3NRIce
  code:
    captchaAppId: 2033594012
    appSecretKey: 0TlT75IKpUdBuvhHgxfmrTQ**
