server:
  port: 80 # 服务端口
spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-gateway # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: 110.42.224.240:8848 # nacos服务地址
    gateway:
      discovery:
        locator:
          enabled: true # gateway可以发现nacos中的微服务，并自动生成转发路由
      routes:
        - id: service-acl
          uri: lb://service-acl
          predicates:
            - Path=/admin/acl/**
        - id: service-core
          uri: lb://service-core
          predicates:
            - Path=/admin/core/**/**,/ucenterservice/apimember/**/**,/front/core/**
        - id: service-oss
          uri: lb://service-oss
          predicates:
            - Path=/eduoss/fileoss/**

