server:
  port: 8001 # 服务端口

#spirng基础配置
spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-acl # 服务名
  # mysql数据库连接
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fxb?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: root
  #设置json日期统一返回格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #微服务注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 47.115.35.176:8848 # nacos服务地址
  #redis配置
  redis:
    host: 47.115.35.176
    port: 6379
    database: 0
    password: 1410357039
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        max-idle: 5
        #最小空闲
        min-idle: 0

#mybatis配置
mybatis-plus: #mybatis
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #日志输出配置
  mapper-locations: classpath:com/jzj/aclservice/mapper/xml/*.xml  #xml文件位置