server:
  port: 8001 # 服务端口

#spirng基础配置
spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-acl # 服务名
  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://你的IP地址/fxb?useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: 你的密码
  #设置json日期统一返回格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #微服务注册中心
  cloud:
    nacos:
      discovery:
        server-addr: nacos地址 # nacos服务地址
  #redis配置
  redis:
    host: 你的redis地址
    port: 6379
    database: 0
    password: 密码
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        max-idle: 5
        #最小空闲
        min-idle: 0

#mybatis配置
mybatis-plus: #mybatis
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #日志输出配置
  mapper-locations: classpath:com/jzj/aclservice/mapper/xml/*.xml  #xml文件位置