#服务端口
server:
  port: 8003
#服务名
spring:
  application:
    name: service-oss
  #环境设置：dev、test、prod
  profiles:
    active: dev
  # Nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: nacos地址
#阿里云 OSS
#不同的服务器，地址不同
aliyun:
  oss:
    endpoint: xx
    keyid: xx
    keysecret: xx
    bucketname: xx

