#服务端口
server:
  port: 8003
#服务名
spring:
  application:
    name: service-oss
  #环境设置：dev、test、prod
  profiles:
    active: dev
  # Nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 110.42.224.240:8848
#阿里云 OSS
#不同的服务器，地址不同
aliyun:
  oss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    keyid: LTAI5tN2Qrd9BRpABEVEP246
    keysecret: JEOzlrD8h4IRDFY5R6FuEWacgBebzn
    bucketname: fxb-jzj

